Shope/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^(?P<category_slug>[-\w]+)/$', views.ProductList,
        name='ProductListByCategory'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.ProductDetail,
        name='ProductDetail'),
    url(r'^$', views.ProductList, name='ProductList'),
]

cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^remove/(?P<product_id>\d+)/$', views.CartRemove, name='CartRemove'),
    url(r'^add/(?P<product_id>\d+)/$', views.CartAdd, name='CartAdd'),
    url(r'^$', views.CartDetail, name='CartDetail'),
]

eshop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cart/', include(('cart.urls', 'cart'), namespace='cart')),
    url(r'^', include(('Shope.urls', 'Shope'), namespace='Shope')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Shope/models.py
from django.db import models
from django.urls import reverse


# Модель категории
class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    def get_absolute_url(self):
        return reverse('Shope:ProductListByCategory', args=[self.slug])

    class Meta:
        ordering = ['name']
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name


# Модель продукта
class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products',
                                 verbose_name="Категория",
                                 on_delete=models.PROTECT)
    name = models.CharField(max_length=200, db_index=True,
                            verbose_name="Название")
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d/', blank=True,
                              verbose_name="Изображение товара")
    description = models.TextField(blank=True, verbose_name="Описание")
    price = models.DecimalField(max_digits=10, decimal_places=2,
                                verbose_name="Цена")
    stock = models.PositiveIntegerField(verbose_name="На складе")
    available = models.BooleanField(default=True, verbose_name="Доступен")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']
        index_together = [
            ['id', 'slug']
        ]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('Shope:ProductDetail', args=[self.id, self.slug])

cart/models.py
from django.db import models

# Create your models here.

myshop/models.py
from django.db import models


# Модель категории
class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ['name']
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name


# Модель продукта
class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products',
                                 verbose_name="Категория")
    name = models.CharField(max_length=200, db_index=True,
                            verbose_name="Название")
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d/', blank=True,
                              verbose_name="Изображение товара")
    description = models.TextField(blank=True, verbose_name="Описание")
    price = models.DecimalField(max_digits=10, decimal_places=2,
                                verbose_name="Цена")
    stock = models.PositiveIntegerField(verbose_name="На складе")
    available = models.BooleanField(default=True, verbose_name="Доступен")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']
        index_together = [
            ['id', 'slug']
        ]

    def __str__(self):
        return self.name

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,
                                      coerce=int)
    update = forms.BooleanField(required=False, initial=False,
                                widget=forms.HiddenInput)

Shope/views.py
from django.shortcuts import render, get_object_or_404
from django.views.decorators.csrf import csrf_protect, csrf_exempt

from .models import Category, Product
from cart.forms import CartAddProductForm
from django.shortcuts import render, get_object_or_404, render_to_response
from .models import Category, Product
from cart.forms import CartAddProductForm


# Страница с товарами
def ProductList(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'shop/product/list.html', {
        'category': category,
        'categories': categories,
        'products': products
    })


# Страница товара
def ProductDetail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'shop/product/detail.html',
                             {'product': product,
                              'cart_product_form': cart_product_form})

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.csrf import csrf_exempt, csrf_protect
from django.views.decorators.http import require_POST
from Shope.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@csrf_exempt
@require_POST
@csrf_protect
def CartAdd(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'],
                                  update_quantity=cd['update'])
    return redirect('cart:CartDetail')


def CartRemove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:CartDetail')


def CartDetail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
                                        initial={
                                            'quantity': item['quantity'],
                                            'update': True
                                        })
    return render(request, 'cart/detail.html', {'cart': cart})

templates/cart/detail.html
{% extends "shop/base.html" %}
{% block title %}
  Ваша корзина товаров
{% endblock %}
{% block content %}
  <h1>Ваша корзина товаров</h1>
  <table class="cart">
    <thead>
      <tr>
        <th>Изображение</th>
        <th>Продукт</th>

        <th>Удалить</th>
        <th>Полная цена</th>
        <th>Цена</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with product=item.product %}
          <tr>
            <td>
              <a href="{{ product.get_absolute_url }}">
                <img src="{{ product.image.url }}" alt="" />
              </a>
            </td>
            <td>{{ product.name }}</td>
                <form action="{% url "cart:CartAdd" product.id %}" method="post" class="add">
                    {{ item.update_quantity_form.quantity }}
                    {{ item.update_quantity_form.update }}
                    {% csrf_token %}
                    <input type="submit" value="Обновить">
                </form>
            <td><a href="{% url "cart:CartRemove" product.id %}">Удалить</a></td>
            <td class="num">{{ item.price }} руб.</td>
            <td class="num">{{ item.total_price }} руб.</td>
          </tr>
        {% endwith %}
      {% endfor %}
        <tr class="total">
          <td>Total</td>
          <td colspan="4"></td>
          <td class="num">{{ cart.get_total_price }} руб.</td>
        </tr>
    </tbody>
  </table>
  <p class="text-right">
    <a href="{% url "Shope:ProductList"%}" class="btn">Продолжить Шопинг</a>
    <a href="#">Оформить заказ</a>
  </p>
{% endblock %}

templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}{% endblock %}</title>

  <!-- Styles -->
  <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
  <link rel="stylesheet" href="{% static "css/style.css" %}">
    <link rel="stylesheet" href="{% static "css/1.css" %}">
</head>
<body>
  <section id="header">
    <div class="top container">
      Мой Онлайн-Магазин
    </div>
    <div class="top-bl">
      <div class="container">
        <div class="cart">
          {% with total_items=cart|length %}
            {% if cart|length > 0 %}
              Ваша корзина:
              <a href="{% url "cart:CartDetail" %}">
                {{ total_items }} тов. {{ cart.get_total_price }} руб.
              </a>
            {% else %}
              Корзина пустая
            {% endif %}
          {% endwith %}
        </div>
      </div>
    </div>
  </section>
  <section id="content row" class="container">
    {% block content %}{% endblock %}
  </section>
</body>
</html>

templates/shop/product/detail.html
{% extends "shop/base.html" %}

{% load static %}

{% block title %}
  {{ product.name }}
{% endblock %}

{% block content %}
  <div class="product-detail">
    <div class="col-sm-4">
      <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no-image.jpg"%}{% endif %}" class="img-responsive">
    </div>
    <div class="col-sm-8">
      <h1>{{ product.name }}</h1>
      <h2><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h2>
      <p class="price">{{ product.price }} руб.</p>
      <form action="{% url "cart:CartAdd" product.id %}" method="post" class="add">
        {{ cart_product_form }}
        {% csrf_token %}
        <input type="submit" value="Добавить в корзину">
      </form>
      <span>{{ product.description | linebreaks}}</span>
    </div>
  </div>
{% endblock %}

templates/shop/product/list.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}
  {% if category %} {{ category.name }} {% else %} Страница товаров {% endif %}
{% endblock %}
{% block content %}
  <div id="sidebar" class="col-sm-3">
    <h3>Категории</h3>
    <ul>
      <li {% if not category %} class="selected" {% endif %}>
        <a href="{% url "Shope:ProductList" %}">Все</a>
      </li>
      {% for cat in categories %}
        <li {% if category.slug == cat.slug %} class="selected" {% endif %}>
          <a href="{{ cat.get_absolute_url }}">{{ cat.name }}</a>
        </li>
      {% endfor %}
    </ul>
  </div>
  <div id="main" class="product_list col-sm-9">
    <h1>{% if category %}{{ category.name }}{% else %}Товары{% endif %}</h1>
    <div class="items row">
      {% for product in products %}
        <div class="item col-sm-4">
          <a href="{{ product.get_absolute_url }}">
            <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no-image.jpg"%}{% endif %}" class="img-responsive">
          </a>
          <a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br>
          {{ product.price }} Euro
        </div>
      {% endfor %}
    </div>
  </div>
    <div class="mapouter"><div class="gmap_canvas"><iframe width="600" height="500" id="gmap_canvas" src="https://maps.google.com/maps?q=%D0%98%D0%BD%D1%82%D0%B5%D1%80%D0%BD%D0%B5%D1%82-%D0%BC%D0%B0%D0%B3%D0%B0%D0%B7%D0%B8%D0%BD%20%D0%BA%D0%BE%D0%B6%D0%B0%D0%BD%D1%8B&t=&z=17&ie=UTF8&iwloc=&output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe><a href="https://www.emojilib.com"></a></div><style>.mapouter{position:relative;text-align:right;height:500px;width:600px;}.gmap_canvas {overflow:hidden;background:none!important;height:500px;width:600px;}</style></div>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

<div class="wrapper">
  <ul>
    <li><i class="fa fa-facebook" aria-hidden="true"></i></li>
    <li><i class="fa fa-twitter" aria-hidden="true"></i></li>
    <li><i class="fa fa-google-plus" aria-hidden="true"></i></li>
    <li><i class="fa fa-reddit" aria-hidden="true"></i></li>
    <li><i class="fa fa-whatsapp" aria-hidden="true"></i></li>
  </ul>
</div>

{% endblock %}
</code>
</pre>